//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarif_Proje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Mesajlar
    {
        public short ID { get; set; }
        public string BASLIK { get; set; }
        public string MAİL { get; set; }
        public string ICERIK { get; set; }
        public string GONDEREN { get; set; }
    }
}
