//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarif_Proje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_GununYemegi
    {
        public short ID { get; set; }
        public string AD { get; set; }
        public string MALZEME { get; set; }
        public string TARİF { get; set; }
        public string RESİM { get; set; }
        public Nullable<byte> PUAN { get; set; }
        public Nullable<System.DateTime> TARİH { get; set; }
    }
}
