//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarif_Proje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Yemekler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Yemekler()
        {
            this.Tbl_Yorumlar = new HashSet<Tbl_Yorumlar>();
        }
    
        public short ID { get; set; }
        public string AD { get; set; }
        public string MALZEME { get; set; }
        public string TARİF { get; set; }
        public string RESİM { get; set; }
        public Nullable<System.DateTime> TARİH { get; set; }
        public byte PUAN { get; set; }
        public Nullable<short> KategoriID { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string IdValue { get; set; }
        public Nullable<byte> AdminId { get; set; }
    
        public virtual Tbl_Kategoriler Tbl_Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Yorumlar> Tbl_Yorumlar { get; set; }
        public virtual Tbl_Yonetici Tbl_Yonetici { get; set; }
    }
}
